export GOPATH=$HOME/code/go
export GOWORKSPACE=$GOPATH/src/github.com/cmacrae
export HOME=/Users/cmacrae
EDITOR=/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9/emacsclient
PAGER=less
CVSROOT=~/code/pkgsrc
CVSEDITOR=emacs
CVS_RSH=ssh

# Evaluate system PATH
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi

# Set PATH precedence in favour of /opt/pkg
export PATH=/opt/pkg/bin:/opt/pkg/sbin:/opt/pkg/gcc5/bin:$PATH
