export GOPATH=$HOME/code/go
export GOWORKSPACE=$GOPATH/src/github.com/cmacrae
export HOME=/Users/cmacrae
EDITOR=emacs
PAGER=less
CVSROOT=~/code/pkgsrc
CVSEDITOR=emacs
CVS_RSH=ssh

# Evaluate system PATH
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
