# Functions
autoload -Uz zutil
autoload -Uz compinit
autoload -Uz complist
autoload -Uz colors
autoload -Uz vcs_info

# Bindings
bindkey -e
bindkey '^R' history-incremental-search-backward # Fix reverse search in tmux

# Activation
compinit
colors

# Source other configs
for file in $HOME/.zsh/rc/*.zsh; do
  source $file
done

# Prompts
if [[ ! -n ${INSIDE_EMACS} ]]; then
export "PROMPT=
%{$fg[blue]%}%m %{$fg[red]%}$ %{$reset_color%}"
export "RPROMPT=%{$fg[red]%}%~%f%b"
else
export "PROMPT=
%{$fg[blue]%}%~ %{$fg[red]%}$ %f%b"
fi

# Evaluate system PATH
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi

# SSH Keychain
eval $(keychain --quiet --eval --agents ssh id_rsa)
