# Functions
autoload -Uz zutil
autoload -Uz compinit
autoload -Uz complist
autoload -Uz colors
autoload -Uz vcs_info

# Bindings
bindkey -e
bindkey '^R' history-incremental-search-backward # Fix reverse search in tmux

# Activation
compinit
colors

# Source other configs
for file in $HOME/.zsh/rc/*.zsh; do
  source $file
done

# Prompts
export "PROMPT=
%{$fg[blue]%}%m %{$fg[red]%}$ %{$reset_color%}"

if [[ ! -n ${INSIDE_EMACS} ]]; then
   export "RPROMPT=%{$fg[red]%}%~%f%b"
fi

# Evaluate system PATH
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi

# Set PATH precedence in favour of /opt/pkg/{bin,sbin}
export PATH=/opt/pkg/bin:/opt/pkg/sbin:/opt/pkg/gcc5/bin:$PATH
