#!/bin/sh

DIR=~/code/git/dotfiles
osx_keybindings(){
    if [ ! -d ~/Library/KeyBindings ]; then
	mkdir ~/Library/KeyBindings
    fi

    cat > ~/Library/KeyBindings/DefaultKeyBinding.dict <<EOF
{
  "^ " = setMark:;
  "^/" = undo:;
  "^u" = deleteToBeginningOfParagraph:;
  "^w" = deleteToMark:;
  "^x" = {
    "^x" = swapWithMark:;
    "^m" = selectToMark:;
  };
  "^V" = pageDownAndModifySelection:;
  "~@" = selectWord:;
  "~b" = moveWordBackward:;
  "~c" = (capitalizeWord:, moveForward:, moveForward:);
  "~d" = deleteWordForward:;
  "~f" = moveWordForward:;
  "~l" = (lowercaseWord:, moveForward:, moveForward:);
  "~u" = (uppercaseWord:, moveForward:, moveForward:);
  "~v" = pageUp:;
  "~w" = (deleteToMark:, setMark:, yank:, swapWithMark:);
  "~B" = moveWordBackwardAndModifySelection:;
  "~F" = moveWordForwardAndModifySelection:;
  "~V" = pageUpAndModifySelection:;
}
EOF
    echo "OS X keybindings applied"
}

symlinker() {
    echo "Symlinking dotfiles"
    for dot in $(ls dots) ; do
	if [ -z ~/.$dot ] || [ -d ~/.$dot ]; then
	    rm -rf ~/.$dot
	fi
	ln -sf $DIR/dots/$dot ~/.$dot
    done

    echo "You're all set!"
}

getAntigen() {
    if [ ! -f dots/zsh/rc/antigen.zsh ]; then
	curl https://cdn.rawgit.com/zsh-users/antigen/v1.2.2/bin/antigen.zsh > antigen.zsh
    fi
}

osx_keybindings
getAntigen
symlinker
exit $?
