#!/bin/sh

DIR=~/code/git/dotfiles
osx_keybindings(){
    if [ ! -d ~/Library/KeyBindings ]; then
	mkdir ~/Library/KeyBindings
    fi

    cat > ~/Library/KeyBindings/DefaultKeyBinding.dict <<EOF
{
  "^ " = setMark:;
  "^/" = undo:;
  "^u" = deleteToBeginningOfParagraph:;
  "^w" = deleteToMark:;
  "^x" = {
    "^x" = swapWithMark:;
    "^m" = selectToMark:;
  };
  "^V" = pageDownAndModifySelection:;
  "~@" = selectWord:;
  "~b" = moveWordBackward:;
  "~c" = (capitalizeWord:, moveForward:, moveForward:);
  "~d" = deleteWordForward:;
  "~f" = moveWordForward:;
  "~l" = (lowercaseWord:, moveForward:, moveForward:);
  "~u" = (uppercaseWord:, moveForward:, moveForward:);
  "~v" = pageUp:;
  "~w" = (deleteToMark:, setMark:, yank:, swapWithMark:);
  "~B" = moveWordBackwardAndModifySelection:;
  "~F" = moveWordForwardAndModifySelection:;
  "~V" = pageUpAndModifySelection:;
}
EOF
    echo "OS X keybindings applied"
}

symlinker() {
    echo "Symlinking dotfiles"
    for dot in $(ls dots) ; do
	if [ -z ~/.$dot ] || [ -d ~/.$dot ]; then
	    rm -rf ~/.$dot
	fi
	ln -sf $DIR/dots/$dot ~/.$dot
    done

    if [ ! -d ~/.emacs.d ]; then
	mkdir ~/.emacs.d
    fi
    ln -sf $DIR/emacs/init.el ~/.emacs.d/init.el
    ln -sf -F $DIR/emacs/modules ~/.emacs.d

    # emacs packages not available in repos
    if [ ! -d ~/.emacs.d/vendor ]; then
	mkdir ~/.emacs.d/vendor
	# znc for erc
	curl -sk -o ~/.emacs.d/vendor/znc.el https://raw.githubusercontent.com/sshirokov/ZNC.el/master/znc.el
    fi

    if [ ! -f ~/.emacs.d/custom.el ]; then
	touch ~/.emacs.d/custom.el
    fi

    if [ ! -d ~/org ]; then
	mkdir ~/org
    fi

    echo "You're all set!"
}

symlinker
exit $?
