alias ls="ls -G"
alias rm="rm -i"
alias cp="cp -i"
alias ytdl="youtube-dl -f mp4 --max-quality mp4 -o '%(title)s.%(ext)s'"
alias gows="cd $GOWORKSPACE"
alias e="emacs"
alias ansible-playbook="ansible-playbook --ask-vault-pass --private-key ~/.ssh/ansible_rsa"
alias ansible="ansible --ask-vault-pass --private-key ~/.ssh/ansible_rsa"
