GOROOT=/usr/local/go
GOPATH=$HOME/code/go
PLAN9=/usr/local/plan9
PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:$GOROOT/bin:$GOPATH/bin:$PLAN9/bin"
PKG_PATH=ftp://mirror.ox.ac.uk/pub/OpenBSD/snapshots/packages/amd64/
EDITOR=vim
PAGER=less
