# Functions
fpath=($HOME/.zsh/functions $fpath)

export LC_CTYPE=en_US.UTF-8

# OpenBSD package mirror
export PKG_PATH=ftp://mirror.ox.ac.uk/pub/OpenBSD/snapshots/packages/amd64/

# Color wrapper
export PATH="/usr/local/lib/cw:/usr/local/lib/cw:/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin"

# Set text editor
export EDITOR=vim

autoload -U zutil
autoload -U compinit
autoload -U complist
autoload -U colors

bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward
bindkey '^K' kill-whole-line
bindkey "\e[H" beginning-of-line        # Home (xorg)
bindkey "\e[1~" beginning-of-line       # Home (console)
bindkey "\e[4~" end-of-line             # End (console)
bindkey "\e[F" end-of-line              # End (xorg)
bindkey "\e[2~" overwrite-mode          # Ins
bindkey "\e[3~" delete-char             # Delete
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
bindkey '^R' history-incremental-search-backward # Fix reverse search in tmux

# Activation
compinit
colors

# Resource files
for file in $HOME/.zsh/rc/*.zsh; do
	source $file
done

# Prompts
export "PROMPT=
%{$fg[cyan]%}%m %{$fg[red]%}$ %{$reset_color%}"
export "RPROMPT=%{$fg[red]%}%~%f%b"
