#! /bin/sh

LDESKS='One Three Five'
RDESKS='Two Four Six'

bspc desktop Desktop1 -n One
bspc desktop Desktop2 -n Two
bspc monitor HDMI1 -a $LDESKS
bspc monitor HDMI2 -a $RDESKS

bspc config wm_name       "bspwm"
bspc config border_width  5
bspc config window_gap    5

bspc config focused_border_color         '#da637e'
bspc config active_border_color          '#332d29'
bspc config presel_border_color          '#CFE5A7'
bspc config normal_locked_border_color   '#A2DCC3'
bspc config focused_locked_border_color  '#CFE5A7'
bspc config active_locked_border_color   '#FB7AA1'

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
bspc config focus_follows_monitor  true
bspc config adaptative_raise       true
bspc config apply_shadow_property  true
bspc config auto_cancel            true

bspc rule -a xombrero desktop=One
bspc rule -a MPlayer desktop=Three floating=on focus=on follow=on
bspc rule -a zathura desktop=Five focus=on follow=on
bspc rule -a nitrogen floating=on
