#! /bin/sh

bspc monitor -d One Two Three Four

bspc config wm_name       "bspwm"
bspc config border_width  2
bspc config window_gap    10

bspc config focused_border_color         '#1c728c'
bspc config active_border_color          '#186150'
bspc config presel_border_color          '#CFE5A7'
bspc config normal_locked_border_color   '#A2DCC3'
bspc config focused_locked_border_color  '#CFE5A7'
bspc config active_locked_border_color   '#FB7AA1'

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
bspc config focus_follows_monitor  true
bspc config adaptative_raise       true
bspc config apply_shadow_property  true
bspc config auto_cancel            true

bspc config -m HDMI1 top_padding 22

bspc rule -a xombrero desktop=Two
bspc rule -a MPlayer desktop=Three floating=on focus=on follow=on
bspc rule -a xmessage floating=on focus=on
