#! /bin/sh

FIRST_DESK=One
DESKS='Two Three Four'
bspc rename Desktop01 $FIRST_DESK
bspc add_in Monitor01 $DESKS

bspc rule MPlayer Four floating
#bspc rule Download floating
#bspc rule Gifview floating

bspc set border_width   5
#bspc set window_gap    0
bspc set top_padding   -22

bspc set focused_border_color         '#1c728c'
bspc set active_border_color          '#186150'
bspc set presel_border_color          '#CFE5A7'
bspc set normal_locked_border_color   '#A2DCC3'
bspc set focused_locked_border_color  '#CFE5A7'
bspc set active_locked_border_color   '#FB7AA1'

bspc set borderless_monocle     true
bspc set gapless_monocle        true
bspc set focus_follows_pointer   true
bspc set adaptative_raise       true
