#!/bin/sh

 ####################################
# Symlink setup for dotfiles on OS X #
 ####################################

# Check that it's OS X
if [ `uname -s` != "Darwin" ]; then
  echo "This doesn't look like OS X: `uname -s`" ; exit
fi

# Variables
DIR=~/code/git/dotfiles/osx                                       			    # dotfiles directory
CONFDIR=~/code/git/dotfiles/osx/config                            		    	# config directory
DOTS="zshrc zsh vimrc vim xinitrc tmux.conf Xdefaults xombrero.conf"        # files/folders to symlink
CONFS="bspwm sxhkd ranger"                                               	  # dots for confdir

# cd to the new dotfile directory
cd $DIR

# Backup any existing dotfiles and symlink the new ones
echo "Symlinking dotfiles"

for file in $DOTS; do
    if [ -z ~/.$file ] || [ -d ~/.$file ]; then
      rm -rf ~/.$file
    fi
    ln -sf $DIR/$file ~/.$file
done

for file in $CONFS; do
  if [ -z ~/.config/$file ] || [ -d ~/.config/$file ]; then
    rm -rf ~/.config/$file
  fi
    ln -sf $CONFDIR/$file ~/.config/$file
done

# Set irssi password
if [ -d ~/.irssi ]; then
  rm -rf ~/.irssi
fi
cp -rf irssi ~/.irssi
echo "Please enter your ZNC server's password:"
read -s PASSWORD
sed -i .bak "s/XXXX/${PASSWORD}/g" ~/.irssi/config ; rm -f ~/.irssi/config.bak

if [ -e ~/.vim/bundle/vundle/README.md ]; then
    echo "Looks like you're updating :) Enjoy!"
else
    # Getting Vundle
    echo "Setting up vim bundles..."
    git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle ; vim +BundleInstall +qall
    echo
    echo "You're all set!"
fi  
