#!/bin/sh

 ####################################
# Symlink setup for dotfiles on OS X #
 ####################################

# Check that it's OS X
if [ `uname -s` != "Darwin" ]; then
  echo "This doesn't look like OS X: `uname -s`" ; exit
fi

# Variables
DIR=~/code/git/dotfiles/osx
CONFDIR=${DIR}/config
DOTS="zshrc zshenv zsh tmux.conf Xdefaults"
CONFS="bspwm sxhkd ranger"

# cd to the new dotfile directory
cd $DIR

# Symlink dotfiles
echo "Symlinking dotfiles"
for file in $DOTS; do
    if [ -z ~/.$file ] || [ -d ~/.$file ]; then
      rm -rf ~/.$file
    fi
    ln -sf $DIR/$file ~/.$file
done

# ensure ~/.config is created, then set-up
if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi

for file in $CONFS; do
    if [ -z ~/.config/$file ] || [ -d ~/.config/$file ]; then
	rm -rf ~/.config/$file
    fi
    ln -sf $CONFDIR/$file ~/.config/$file
done

# emacs core configs
if [ ! -d ~/.emacs.d ]; then
    mkdir ~/.emacs.d
fi
ln -sf $DIR/emacs/init.el ~/.emacs.d/init.el
ln -sf -F $DIR/emacs/modules ~/.emacs.d

# emacs packages not available in repos
if [ ! -d ~/.emacs.d/vendor ]; then
    mkdir ~/.emacs.d/vendor
    # znc for erc
    curl -sk -o ~/.emacs.d/vendor/znc.el https://raw.githubusercontent.com/sshirokov/ZNC.el/master/znc.el
    # sane-term
    curl -sk -o ~/.emacs.d/vendor/sane-term.el https://raw.githubusercontent.com/adamrt/sane-term/master/sane-term.el
fi

# Set erc password
cp -f $DIR/emacs/irc.el ~/.emacs.d/modules/irc.el
echo "Please enter your ZNC server's password:"
read -s PASSWORD
sed -i .bak "s/XXXX/${PASSWORD}/g" ~/.emacs.d/modules/irc.el ; rm -f ~/.emacs.d/modules/irc.el.bak
echo "You're all set!"
