# Remove stale bspwm sockets
rm -f /tmp/bspwm* 2>&1 > /dev/null

# Set the homedir
export HOME=/Users/cmacrae
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set the wallpaper
#setbg -i ~/pictures/wallpapers/river-town.jpg  -focus X11 &

# Daemonise URxvt
urxvtd -q -o -f &

# Set cursor
xsetroot -cursor_name left_ptr &

# Start bspwm
sxhkd &
exec bspwm
